# Generated by Django 3.0.3 on 2020-11-10 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('document_title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('priority', models.CharField(choices=[('Select', 'Select'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default=' ', max_length=20)),
                ('new_document_or_process', models.CharField(choices=[('Select', 'Select'), ('Yes', 'Yes'), ('No', 'No')], default=' ', max_length=20)),
                ('are_other_stakeholders_affected', models.CharField(choices=[('Select', 'Select'), ('Yes', 'Yes'), ('No', 'No')], default=' ', max_length=20)),
                ('requested_changes', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
                ('area', models.CharField(choices=[('Select', 'Select'), ('Admin', 'Admin'), ('Asset Prep', 'Asset Prep'), ('Box/Stow', 'Box/Stow'), ('QA', 'QA'), ('Receiving', 'Receiving'), ('Refurb', 'Refurb'), ('Registration', 'Registration'), ('Repair', 'Repair'), ('Shipping', 'Shipping'), ('Test', 'Test')], default=' ', max_length=20)),
                ('status', models.CharField(choices=[('New - Pending Review', 'New - Pending Review'), ('In Progress', 'In Progress'), ('Reject', 'Reject'), ('Closed', 'Closed')], default='New - Pending Review', max_length=20)),
                ('revision_number', models.CharField(default=' ', max_length=3)),
                ('reason_for_change', models.TextField(blank=True, default='')),
                ('file', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('name', models.ForeignKey(default='.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='requests.Request')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
