# Generated by Django 3.0.3 on 2020-11-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='file',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
